[package]
name = "dial"
version = "0.1.0"
authors = ["Honwhy Wang <honwhy.wang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
structopt = "0.3"
may = "0.3.14"
